// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: videoUser.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoUser_Login_FullMethodName = "/VideoUser/Login"
)

// VideoUserClient is the client API for VideoUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoUserClient interface {
	Login(ctx context.Context, in *LoginRep, opts ...grpc.CallOption) (*LoginRes, error)
}

type videoUserClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoUserClient(cc grpc.ClientConnInterface) VideoUserClient {
	return &videoUserClient{cc}
}

func (c *videoUserClient) Login(ctx context.Context, in *LoginRep, opts ...grpc.CallOption) (*LoginRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginRes)
	err := c.cc.Invoke(ctx, VideoUser_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoUserServer is the server API for VideoUser service.
// All implementations must embed UnimplementedVideoUserServer
// for forward compatibility.
type VideoUserServer interface {
	Login(context.Context, *LoginRep) (*LoginRes, error)
	mustEmbedUnimplementedVideoUserServer()
}

// UnimplementedVideoUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoUserServer struct{}

func (UnimplementedVideoUserServer) Login(context.Context, *LoginRep) (*LoginRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedVideoUserServer) mustEmbedUnimplementedVideoUserServer() {}
func (UnimplementedVideoUserServer) testEmbeddedByValue()                   {}

// UnsafeVideoUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoUserServer will
// result in compilation errors.
type UnsafeVideoUserServer interface {
	mustEmbedUnimplementedVideoUserServer()
}

func RegisterVideoUserServer(s grpc.ServiceRegistrar, srv VideoUserServer) {
	// If the following call pancis, it indicates UnimplementedVideoUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoUser_ServiceDesc, srv)
}

func _VideoUser_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRep)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoUserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoUser_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoUserServer).Login(ctx, req.(*LoginRep))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoUser_ServiceDesc is the grpc.ServiceDesc for VideoUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VideoUser",
	HandlerType: (*VideoUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _VideoUser_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "videoUser.proto",
}
