Mysql:
  Host: 127.0.0.1
  Port: 3306
  UserName: root
  PassWord: root
  DataBase: test
Redis:
  Host: 127.0.0.1
  Pass:
  Port: 6379
  DB: 0
  User:
Server:
  Host: 127.0.0.1
  Port: 8081
Elastic:
  Host: 127.0.0.1
  Port: 9200
  User:
  Pass:
AliyunGpt:
  ApiKey: sk-
Mongo:
  Host: 127.0.0.1
  Port: 27017
  User: mongodb
  Pass: root

