// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: videoGoodsClassifiy.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoodsClassifiy_GetGoodsClass_FullMethodName = "/goodsClassifiy/GetGoodsClass"
)

// GoodsClassifiyClient is the client API for GoodsClassifiy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodsClassifiyClient interface {
	GetGoodsClass(ctx context.Context, in *GoodsClassReq, opts ...grpc.CallOption) (*GoodsClassRes, error)
}

type goodsClassifiyClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodsClassifiyClient(cc grpc.ClientConnInterface) GoodsClassifiyClient {
	return &goodsClassifiyClient{cc}
}

func (c *goodsClassifiyClient) GetGoodsClass(ctx context.Context, in *GoodsClassReq, opts ...grpc.CallOption) (*GoodsClassRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodsClassRes)
	err := c.cc.Invoke(ctx, GoodsClassifiy_GetGoodsClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsClassifiyServer is the server API for GoodsClassifiy service.
// All implementations must embed UnimplementedGoodsClassifiyServer
// for forward compatibility.
type GoodsClassifiyServer interface {
	GetGoodsClass(context.Context, *GoodsClassReq) (*GoodsClassRes, error)
	mustEmbedUnimplementedGoodsClassifiyServer()
}

// UnimplementedGoodsClassifiyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoodsClassifiyServer struct{}

func (UnimplementedGoodsClassifiyServer) GetGoodsClass(context.Context, *GoodsClassReq) (*GoodsClassRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsClass not implemented")
}
func (UnimplementedGoodsClassifiyServer) mustEmbedUnimplementedGoodsClassifiyServer() {}
func (UnimplementedGoodsClassifiyServer) testEmbeddedByValue()                        {}

// UnsafeGoodsClassifiyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodsClassifiyServer will
// result in compilation errors.
type UnsafeGoodsClassifiyServer interface {
	mustEmbedUnimplementedGoodsClassifiyServer()
}

func RegisterGoodsClassifiyServer(s grpc.ServiceRegistrar, srv GoodsClassifiyServer) {
	// If the following call pancis, it indicates UnimplementedGoodsClassifiyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoodsClassifiy_ServiceDesc, srv)
}

func _GoodsClassifiy_GetGoodsClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsClassReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsClassifiyServer).GetGoodsClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsClassifiy_GetGoodsClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsClassifiyServer).GetGoodsClass(ctx, req.(*GoodsClassReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodsClassifiy_ServiceDesc is the grpc.ServiceDesc for GoodsClassifiy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodsClassifiy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goodsClassifiy",
	HandlerType: (*GoodsClassifiyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGoodsClass",
			Handler:    _GoodsClassifiy_GetGoodsClass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "videoGoodsClassifiy.proto",
}
